config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do 
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end 
 
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  #フォローした関係のアソシエーション
  #foreign_keyは外部キー
  #has_many :relationships, class_name:"Relationship"では
  #Relationshipsテーブルのどちら(follower,followed)を参照すればいいかわからない
  #なので、fofeign_keyで参照先を指定する
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  
  #フォローされた関係のアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #reverse_of_relationshipsはフォローした関係のアソシエーションと区別と付けるための記述
  
  #一覧画面で使う
   #has_many :架空のテーブル名, through: :中間テーブル名でテーブル同士が中間テーブルを
  #通じて繋がっていることを表現(followerテーブルとfollowedテーブルのつながり)
  #@user.架空のテーブル名と記述することでフォローorフォロワーの一覧を表示できる
  has_many :followings, through: :relationships, source: :followed
  #followingsは中間テーブル(relationships)を通じてfollowedモデルを取得できる
  
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #followersは中間テーブルと通じてfollowerモデルを取得できる
  
  has_many :view_counts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
 
 
  #コントローラで使うメソッドを記述
  
  #フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end 
  
  #フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end 
  
  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end 
  
  #検索方法分岐
  #nameは検索対象であるusersテーブル内のカラム名
  #検索フォームからsearchによって送られてきた内容を条件分岐させる
  #whereメソッドを用い、データベースから該当データを取得し、変数を代入
  #whereメソッドは、「テーブル内の条件に一致したレコードを配列の形で取得できるメソッド
  #whereのLIKE句を使ったあいまい検索の構文
  #モデルクラス.where("列名　LIKE ?"" "%値%) 
  def self.looks(search, word)
    #条件式1
    if search == "perfect_match"
    #処理1
    @user = User.where("name LIKE?","#{word}")
    #条件式2
    elsif search == "forward_match"
      #処理2
      @user = User.where("name LIKE?","#{word}%")
    #条件式3
    elsif search == "backward_match"
      #処理3
      @user = User.where("name LIKE?","%#{word}")
    #条件式4
    elseif search == "partial_match"
      #処理4
      @user = User.where("name LIKE?","%#{word}%")
    else 
      @user = User.all
    end 
  end 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    #一覧ページでフォロー数・フォロワー数を表示するための記述
    #@followings = user.followings
    #@followers = user.followers
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else

      render :edit
    end
    
    #フォロー一覧ページ用のコントローラ
    def followed
      user = User.find(params[:id])
      @user = user.followed_user.page(params[:page]).per(3).reverse_order
      #reverse_orderは「取得した値を逆順に並び替える」
    end 
    
    #フォロワー一覧ページ用のコントローラ
    def follower
      user = User.find(params[:id])
       @user = user.follower_user.page(params[:page]).per(3).reverse_order
    end 
    
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user.following(user) %>
 <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
<% else %>
 <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <% if current_user != user %>
        <!-- !は論理演算子であり、not演算子と呼ばれる
        「!=」と記述すると、比較演算子の「==」の反対の意味である
        値同士が等しくない場合にtrueを返す-->
        <% if current_user.following?(user) %>
        <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn-sm btn-denger" %></td>
        <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %></td>
        <% end %>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%=link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
   <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn-sm btn-denger" %>
   <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
   <% end %>
  <% end %>
</div>
<br>
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followed.html.erb
<h2>Follows Users </h2>
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
      <td><%= user.name %></td>
      <td><%= user.followings.count %>フォロー数</td>
      <td><%= user.followers.count %>フォロワー数</td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
  </tbody>

</table>

app/views/users/follower.html.erb
<h2>Follower User</h2>
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
      <td><%= user.name %></td>
      <td><%= user.followings.count %>フォロー数</td>
      <td><%= user.followers.count %>フォロワー数</td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
  </tbody>

</table>

app/views/users/index.html.erb
<div class='container'>
 <div class='row'>
  <div class='col-md-3'>
 
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
  </div>
  
<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users %>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>