config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do 
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end 
 
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  #ユーザーがログインしているかどうか確認し、ログインしていない場合
  #ユーザーのログインページにリダイレクトするdeviseメソッド
  before_action :authenticate_user!
  
  def search
    #検索フォームから検索モデルparams[:range]を受け取る
    @range = params[:range]
    @word = params[:word]
    
    #if文を用い、検索モデルUser or Bookで分岐条件にする
    if @range == "User"
      #検索フォームから検索方法params[:search],検索ワードparams[:word]を受け取る
      #looksメソッドを用い、検索内容を取得し、変数を代入する
      #検索方法params[:search]と検索ワードparams[:word]を参照して
      #データを検索
      #@usersにUserモデル内での検索結果を代入
      #@booksにBookモデル内での検索結果を代入
      @users = User.looks(params[:search], params[:word])
    else 
      @books = Book.looks(params[:search], params[:word])
    end 
  end 
  #searchアクションの完了
  #検索方法による切替を行うためのに各モデル(Userモデル,Bookモデル)に
  #分岐条件を記述
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<table>
<!--検索対象モデルがUserの時-->
<% if @range == "User" %>
<h2>Users search for "<%= @word %>"</h2>
 <thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
   </tr>
 </thead>
 <tbody>
 <% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image, size:'50, 50' %></td>
    <td><%= user.name %></td>
  </tr>
 <% end %>
 </tbody>
<% else %>
<h2>Books search for "<%= @word %>"</h2>
<!--検索対象モデルがUserではないとき(=検索対象モデルがBookの時-->
 <thead>
   <tr>
     <th></th>
     <th>Title</th>
     <th>Body</th>
   </tr>
 </thead>
 <tbody>
 <% @books.each do |book| %>
   <tr>
     <td></td>
     <td><%= image_tag user.get_profile_image, size:'50, 50' %></td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
   </tr>
 <% end %>
 </tbody>
<% end %>
</table>